// build-dist.ts -- produce an SQLite-style single-file amalgamation in dist/.
//
//   bun cmd/build-dist.ts
//
// Emits two files:
//   dist/djvu.h  -- the public API header (verbatim copy of src/djvu.h)
//   dist/djvu.c  -- the entire decoder as one translation unit: the public
//                   header, then the internal header, then every src/*.c,
//                   concatenated with the local `#include "djvu.h"` /
//                   `#include "djvu_internal.h"` lines stripped out.
//
// A consumer drops both files into their tree and compiles djvu.c like any
// other source. This verifies the result compiles (clang -c) before finishing.
import { $ } from "bun";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

const ROOT = `${import.meta.dir}/..`;
const SRC = join(ROOT, "src");
const DIST = join(ROOT, "dist");

// Same translation-unit order build.ts uses. djvu_internal.h declares every
// cross-module function, so order among the .c files doesn't matter for
// linkage; we keep build.ts's order for a stable, readable amalgamation.
const SRCS = [
  "zptable.c",
  "zpcodec.c",
  "bzz.c",
  "bitmap.c",
  "jb2.c",
  "iw44_zigzag.c",
  "iw44.c",
  "scaler.c",
  "compose.c",
  "document.c",
  "bufread.c",
  "render.c",
  "text.c",
  "outline.c",
  "annot.c",
  "debug.c",
];

// Drop a local-quote include of one of the named headers (system <...>
// includes are left untouched -- they have their own guards).
function stripIncludes(text: string, headers: string[]): string {
  const re = new RegExp(
    `^[ \\t]*#[ \\t]*include[ \\t]+"(?:${headers.join("|")})"[ \\t]*\\r?\\n`,
    "gm",
  );
  return text.replace(re, "");
}

function banner(title: string): string {
  const bar = "=".repeat(69);
  return `/* ${bar}\n * ${title}\n * ${bar} */\n`;
}

mkdirSync(DIST, { recursive: true });

// 1. Public header: verbatim copy.
const publicHeader = readFileSync(join(SRC, "djvu.h"), "utf8");
writeFileSync(join(DIST, "djvu.h"), publicHeader);

// 2. Amalgamated source.
const parts: string[] = [];
parts.push(
  `/* djvu.c -- single-file amalgamation of the C DjVu decoder.\n` +
    ` *\n` +
    ` * Generated by cmd/build-dist.ts -- do not edit by hand. Edit the sources\n` +
    ` * under src/ and regenerate with \`bun cmd/build-dist.ts\`.\n` +
    ` *\n` +
    ` * Pairs with the public header djvu.h (same dir). Compile djvu.c directly.\n` +
    ` */\n`,
);

// Inline the public header (so djvu.c is self-contained), then the internal
// header with its own `#include "djvu.h"` removed (already inlined above).
parts.push(banner("djvu.h (public API)"));
parts.push(publicHeader.trimEnd() + "\n");

const internal = readFileSync(join(SRC, "djvu_internal.h"), "utf8");
parts.push(banner("djvu_internal.h (internal declarations)"));
parts.push(stripIncludes(internal, ["djvu\\.h"]).trimEnd() + "\n");

// Each translation unit, with the local internal-header include removed.
for (const name of SRCS) {
  const code = readFileSync(join(SRC, name), "utf8");
  parts.push(banner(`src/${name}`));
  parts.push(stripIncludes(code, ["djvu_internal\\.h", "djvu\\.h"]).trimEnd() + "\n");
}

const amalgamated = parts.join("\n");
writeFileSync(join(DIST, "djvu.c"), amalgamated);

const hLines = publicHeader.split("\n").length;
const cLines = amalgamated.split("\n").length;
console.log(`wrote dist/djvu.h (${hLines} lines)`);
console.log(`wrote dist/djvu.c (${cLines} lines, ${SRCS.length} modules)`);

// 3. Verify it compiles as a single translation unit.
console.log("compiling dist/djvu.c (clang -c)...");
const obj = join(DIST, "djvu.o");
if (existsSync(obj)) await $`rm -f ${obj}`.nothrow();
const r = await $`clang -std=c11 -O1 -Wall -Wextra -D_CRT_SECURE_NO_WARNINGS -c ${join(DIST, "djvu.c")} -o ${obj}`
  .cwd(DIST)
  .nothrow();
if (r.exitCode !== 0) {
  console.error("amalgamation FAILED to compile");
  process.exit(1);
}
if (existsSync(obj)) await $`rm -f ${obj}`.nothrow();
console.log("amalgamation compiles cleanly ✓");
